apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: vol-pv
spec:
  accessModes: 
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  hostPath:
    path: /data/ankit
    type: DirectoryOrCreate
