apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: vol-pvc

spec:
  volumeName: vol-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi 